num1 = int(input("Enter the first number: "))
num2 = int(input("Enter the second number: "))
num3 = int(input("Enter the third number: "))
sum = num1 + num2 + num3
product = num1 * num2 * num3
average = sum / 3
print (f"sum = {sum}")
print (f"product = {product}")
print (f"average = {average}")